use esperto::types::Scalar;
use sdl3::gamepad::{Axis, Button};
use sdl3::keyboard;
use serde::{Deserialize, Serialize};
use std::fmt::{Display, Formatter};

#[derive(Copy, Clone, Debug, Hash, PartialEq, Eq, Deserialize, Serialize, Scalar, Ord, PartialOrd, Default)]
pub enum SdlKeycode {
   ScancodeMask,
   #[default]
   Unknown,
   Return,
   Escape,
   Backspace,
   Tab,
   Space,
   Exclaim,
   DblApostrophe,
   Hash,
   Dollar,
   Percent,
   Ampersand,
   Apostrophe,
   LeftParen,
   RightParen,
   Asterisk,
   Plus,
   Comma,
   Minus,
   Period,
   Slash,
   _0,
   _1,
   _2,
   _3,
   _4,
   _5,
   _6,
   _7,
   _8,
   _9,
   Colon,
   Semicolon,
   Less,
   Equals,
   Greater,
   Question,
   At,
   LeftBracket,
   Backslash,
   RightBracket,
   Caret,
   Underscore,
   Grave,
   A,
   B,
   C,
   D,
   E,
   F,
   G,
   H,
   I,
   J,
   K,
   L,
   M,
   N,
   O,
   P,
   Q,
   R,
   S,
   T,
   U,
   V,
   W,
   X,
   Y,
   Z,
   LeftBrace,
   Pipe,
   RightBrace,
   Tilde,
   Delete,
   PlusMinus,
   CapsLock,
   F1,
   F2,
   F3,
   F4,
   F5,
   F6,
   F7,
   F8,
   F9,
   F10,
   F11,
   F12,
   PrintScreen,
   ScrollLock,
   Pause,
   Insert,
   Home,
   PageUp,
   End,
   PageDown,
   Right,
   Left,
   Down,
   Up,
   NumLockClear,
   KpDivide,
   KpMultiply,
   KpMinus,
   KpPlus,
   KpEnter,
   Kp1,
   Kp2,
   Kp3,
   Kp4,
   Kp5,
   Kp6,
   Kp7,
   Kp8,
   Kp9,
   Kp0,
   KpPeriod,
   Application,
   Power,
   KpEquals,
   F13,
   F14,
   F15,
   F16,
   F17,
   F18,
   F19,
   F20,
   F21,
   F22,
   F23,
   F24,
   Execute,
   Help,
   Menu,
   Select,
   Stop,
   Again,
   Undo,
   Cut,
   Copy,
   Paste,
   Find,
   Mute,
   VolumeUp,
   VolumeDown,
   KpComma,
   KpEqualsAs400,
   AltErase,
   SysReq,
   Cancel,
   Clear,
   Prior,
   Return2,
   Separator,
   Out,
   Oper,
   ClearAgain,
   CrSel,
   ExSel,
   Kp00,
   Kp000,
   ThousandsSeparator,
   DecimalSeparator,
   CurrencyUnit,
   CurrencySubunit,
   KpLeftParen,
   KpRightParen,
   KpLeftBrace,
   KpRightBrace,
   KpTab,
   KpBackspace,
   KpA,
   KpB,
   KpC,
   KpD,
   KpE,
   KpF,
   KpXor,
   KpPower,
   KpPercent,
   KpLess,
   KpGreater,
   KpAmpersand,
   KpDblAmpersand,
   KpVerticalBar,
   KpDblVerticalBar,
   KpColon,
   KpHash,
   KpSpace,
   KpAt,
   KpExclam,
   KpMemStore,
   KpMemRecall,
   KpMemClear,
   KpMemAdd,
   KpMemSubtract,
   KpMemMultiply,
   KpMemDivide,
   KpPlusMinus,
   KpClear,
   KpClearEntry,
   KpBinary,
   KpOctal,
   KpDecimal,
   KpHexadecimal,
   LCtrl,
   LShift,
   LAlt,
   LGui,
   RCtrl,
   RShift,
   RAlt,
   RGui,
   Mode,
   Sleep,
   Wake,
   ChannelIncrement,
   ChannelDecrement,
   MediaPlay,
   MediaPause,
   MediaRecord,
   MediaFastForward,
   MediaRewind,
   MediaNextTrack,
   MediaPreviousTrack,
   MediaStop,
   MediaEject,
   MediaPlayPause,
   MediaSelect,
   AcNew,
   AcOpen,
   AcClose,
   AcExit,
   AcSave,
   AcPrint,
   AcProperties,
   AcSearch,
   AcHome,
   AcBack,
   AcForward,
   AcStop,
   AcRefresh,
   AcBookmarks,
   SoftLeft,
   SoftRight,
   Call,
   EndCall,

   North,
   East,
   South,
   West,
   Back,
   Guide,
   Start,
   LeftStick,
   RightStick,
   LeftShoulder,
   RightShoulder,
   DPadUp,
   DPadDown,
   DPadLeft,
   DPadRight,
   Misc1,
   Misc2,
   Misc3,
   Misc4,
   Misc5,
   RightPaddle1,
   LeftPaddle1,
   RightPaddle2,
   LeftPaddle2,
   Touchpad,

   LeftX,
   LeftY,
   RightX,
   RightY,
   TriggerLeft,
   TriggerRight,
}

// impl Keycode for SdlKeycode {}

impl Into<u16> for SdlKeycode {
   fn into(self) -> u16 {
      self as u16
   }
}

impl Into<usize> for SdlKeycode {
   fn into(self) -> usize {
      self as usize
   }
}

impl Into<u16> for &SdlKeycode {
   fn into(self) -> u16 {
      *self as u16
   }
}

impl Into<usize> for &SdlKeycode {
   fn into(self) -> usize {
      *self as usize
   }
}

impl Display for SdlKeycode {
   fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
      write!(f, "{self:?}")
   }
}

impl From<Axis> for SdlKeycode {
   fn from(axis: Axis) -> Self {
      match axis {
         Axis::LeftX => SdlKeycode::LeftX,
         Axis::LeftY => SdlKeycode::LeftY,
         Axis::RightX => SdlKeycode::RightX,
         Axis::RightY => SdlKeycode::RightY,
         Axis::TriggerLeft => SdlKeycode::TriggerLeft,
         Axis::TriggerRight => SdlKeycode::TriggerRight,
      }
   }
}

impl From<Button> for SdlKeycode {
   fn from(button: Button) -> Self {
      match button {
         Button::North => SdlKeycode::North,
         Button::East => SdlKeycode::East,
         Button::South => SdlKeycode::South,
         Button::West => SdlKeycode::West,
         Button::Back => SdlKeycode::Back,
         Button::Guide => SdlKeycode::Guide,
         Button::Start => SdlKeycode::Start,
         Button::LeftStick => SdlKeycode::LeftStick,
         Button::RightStick => SdlKeycode::RightStick,
         Button::LeftShoulder => SdlKeycode::LeftShoulder,
         Button::RightShoulder => SdlKeycode::RightShoulder,
         Button::DPadUp => SdlKeycode::DPadUp,
         Button::DPadDown => SdlKeycode::DPadDown,
         Button::DPadLeft => SdlKeycode::DPadLeft,
         Button::DPadRight => SdlKeycode::DPadRight,
         Button::Misc1 => SdlKeycode::Misc1,
         Button::Misc2 => SdlKeycode::Misc2,
         Button::Misc3 => SdlKeycode::Misc3,
         Button::Misc4 => SdlKeycode::Misc4,
         Button::Misc5 => SdlKeycode::Misc5,
         Button::RightPaddle1 => SdlKeycode::RightPaddle1,
         Button::LeftPaddle1 => SdlKeycode::LeftPaddle1,
         Button::RightPaddle2 => SdlKeycode::RightPaddle2,
         Button::LeftPaddle2 => SdlKeycode::LeftPaddle2,
         Button::Touchpad => SdlKeycode::Touchpad,
      }
   }
}

impl From<keyboard::Keycode> for SdlKeycode {
   fn from(keycode: keyboard::Keycode) -> Self {
      match keycode {
         keyboard::Keycode::ScancodeMask => SdlKeycode::ScancodeMask,
         keyboard::Keycode::Unknown => SdlKeycode::Unknown,
         keyboard::Keycode::Return => SdlKeycode::Return,
         keyboard::Keycode::Escape => SdlKeycode::Escape,
         keyboard::Keycode::Backspace => SdlKeycode::Backspace,
         keyboard::Keycode::Tab => SdlKeycode::Tab,
         keyboard::Keycode::Space => SdlKeycode::Space,
         keyboard::Keycode::Exclaim => SdlKeycode::Exclaim,
         keyboard::Keycode::DblApostrophe => SdlKeycode::DblApostrophe,
         keyboard::Keycode::Hash => SdlKeycode::Hash,
         keyboard::Keycode::Dollar => SdlKeycode::Dollar,
         keyboard::Keycode::Percent => SdlKeycode::Percent,
         keyboard::Keycode::Ampersand => SdlKeycode::Ampersand,
         keyboard::Keycode::Apostrophe => SdlKeycode::Apostrophe,
         keyboard::Keycode::LeftParen => SdlKeycode::LeftParen,
         keyboard::Keycode::RightParen => SdlKeycode::RightParen,
         keyboard::Keycode::Asterisk => SdlKeycode::Asterisk,
         keyboard::Keycode::Plus => SdlKeycode::Plus,
         keyboard::Keycode::Comma => SdlKeycode::Comma,
         keyboard::Keycode::Minus => SdlKeycode::Minus,
         keyboard::Keycode::Period => SdlKeycode::Period,
         keyboard::Keycode::Slash => SdlKeycode::Slash,
         keyboard::Keycode::_0 => SdlKeycode::_0,
         keyboard::Keycode::_1 => SdlKeycode::_1,
         keyboard::Keycode::_2 => SdlKeycode::_2,
         keyboard::Keycode::_3 => SdlKeycode::_3,
         keyboard::Keycode::_4 => SdlKeycode::_4,
         keyboard::Keycode::_5 => SdlKeycode::_5,
         keyboard::Keycode::_6 => SdlKeycode::_6,
         keyboard::Keycode::_7 => SdlKeycode::_7,
         keyboard::Keycode::_8 => SdlKeycode::_8,
         keyboard::Keycode::_9 => SdlKeycode::_9,
         keyboard::Keycode::Colon => SdlKeycode::Colon,
         keyboard::Keycode::Semicolon => SdlKeycode::Semicolon,
         keyboard::Keycode::Less => SdlKeycode::Less,
         keyboard::Keycode::Equals => SdlKeycode::Equals,
         keyboard::Keycode::Greater => SdlKeycode::Greater,
         keyboard::Keycode::Question => SdlKeycode::Question,
         keyboard::Keycode::At => SdlKeycode::At,
         keyboard::Keycode::LeftBracket => SdlKeycode::LeftBracket,
         keyboard::Keycode::Backslash => SdlKeycode::Backslash,
         keyboard::Keycode::RightBracket => SdlKeycode::RightBracket,
         keyboard::Keycode::Caret => SdlKeycode::Caret,
         keyboard::Keycode::Underscore => SdlKeycode::Underscore,
         keyboard::Keycode::Grave => SdlKeycode::Grave,
         keyboard::Keycode::A => SdlKeycode::A,
         keyboard::Keycode::B => SdlKeycode::B,
         keyboard::Keycode::C => SdlKeycode::C,
         keyboard::Keycode::D => SdlKeycode::D,
         keyboard::Keycode::E => SdlKeycode::E,
         keyboard::Keycode::F => SdlKeycode::F,
         keyboard::Keycode::G => SdlKeycode::G,
         keyboard::Keycode::H => SdlKeycode::H,
         keyboard::Keycode::I => SdlKeycode::I,
         keyboard::Keycode::J => SdlKeycode::J,
         keyboard::Keycode::K => SdlKeycode::K,
         keyboard::Keycode::L => SdlKeycode::L,
         keyboard::Keycode::M => SdlKeycode::M,
         keyboard::Keycode::N => SdlKeycode::N,
         keyboard::Keycode::O => SdlKeycode::O,
         keyboard::Keycode::P => SdlKeycode::P,
         keyboard::Keycode::Q => SdlKeycode::Q,
         keyboard::Keycode::R => SdlKeycode::R,
         keyboard::Keycode::S => SdlKeycode::S,
         keyboard::Keycode::T => SdlKeycode::T,
         keyboard::Keycode::U => SdlKeycode::U,
         keyboard::Keycode::V => SdlKeycode::V,
         keyboard::Keycode::W => SdlKeycode::W,
         keyboard::Keycode::X => SdlKeycode::X,
         keyboard::Keycode::Y => SdlKeycode::Y,
         keyboard::Keycode::Z => SdlKeycode::Z,
         keyboard::Keycode::LeftBrace => SdlKeycode::LeftBrace,
         keyboard::Keycode::Pipe => SdlKeycode::Pipe,
         keyboard::Keycode::RightBrace => SdlKeycode::RightBrace,
         keyboard::Keycode::Tilde => SdlKeycode::Tilde,
         keyboard::Keycode::Delete => SdlKeycode::Delete,
         keyboard::Keycode::PlusMinus => SdlKeycode::PlusMinus,
         keyboard::Keycode::CapsLock => SdlKeycode::CapsLock,
         keyboard::Keycode::F1 => SdlKeycode::F1,
         keyboard::Keycode::F2 => SdlKeycode::F2,
         keyboard::Keycode::F3 => SdlKeycode::F3,
         keyboard::Keycode::F4 => SdlKeycode::F4,
         keyboard::Keycode::F5 => SdlKeycode::F5,
         keyboard::Keycode::F6 => SdlKeycode::F6,
         keyboard::Keycode::F7 => SdlKeycode::F7,
         keyboard::Keycode::F8 => SdlKeycode::F8,
         keyboard::Keycode::F9 => SdlKeycode::F9,
         keyboard::Keycode::F10 => SdlKeycode::F10,
         keyboard::Keycode::F11 => SdlKeycode::F11,
         keyboard::Keycode::F12 => SdlKeycode::F12,
         keyboard::Keycode::PrintScreen => SdlKeycode::PrintScreen,
         keyboard::Keycode::ScrollLock => SdlKeycode::ScrollLock,
         keyboard::Keycode::Pause => SdlKeycode::Pause,
         keyboard::Keycode::Insert => SdlKeycode::Insert,
         keyboard::Keycode::Home => SdlKeycode::Home,
         keyboard::Keycode::PageUp => SdlKeycode::PageUp,
         keyboard::Keycode::End => SdlKeycode::End,
         keyboard::Keycode::PageDown => SdlKeycode::PageDown,
         keyboard::Keycode::Right => SdlKeycode::Right,
         keyboard::Keycode::Left => SdlKeycode::Left,
         keyboard::Keycode::Down => SdlKeycode::Down,
         keyboard::Keycode::Up => SdlKeycode::Up,
         keyboard::Keycode::NumLockClear => SdlKeycode::NumLockClear,
         keyboard::Keycode::KpDivide => SdlKeycode::KpDivide,
         keyboard::Keycode::KpMultiply => SdlKeycode::KpMultiply,
         keyboard::Keycode::KpMinus => SdlKeycode::KpMinus,
         keyboard::Keycode::KpPlus => SdlKeycode::KpPlus,
         keyboard::Keycode::KpEnter => SdlKeycode::KpEnter,
         keyboard::Keycode::Kp1 => SdlKeycode::Kp1,
         keyboard::Keycode::Kp2 => SdlKeycode::Kp2,
         keyboard::Keycode::Kp3 => SdlKeycode::Kp3,
         keyboard::Keycode::Kp4 => SdlKeycode::Kp4,
         keyboard::Keycode::Kp5 => SdlKeycode::Kp5,
         keyboard::Keycode::Kp6 => SdlKeycode::Kp6,
         keyboard::Keycode::Kp7 => SdlKeycode::Kp7,
         keyboard::Keycode::Kp8 => SdlKeycode::Kp8,
         keyboard::Keycode::Kp9 => SdlKeycode::Kp9,
         keyboard::Keycode::Kp0 => SdlKeycode::Kp0,
         keyboard::Keycode::KpPeriod => SdlKeycode::KpPeriod,
         keyboard::Keycode::Application => SdlKeycode::Application,
         keyboard::Keycode::Power => SdlKeycode::Power,
         keyboard::Keycode::KpEquals => SdlKeycode::KpEquals,
         keyboard::Keycode::F13 => SdlKeycode::F13,
         keyboard::Keycode::F14 => SdlKeycode::F14,
         keyboard::Keycode::F15 => SdlKeycode::F15,
         keyboard::Keycode::F16 => SdlKeycode::F16,
         keyboard::Keycode::F17 => SdlKeycode::F17,
         keyboard::Keycode::F18 => SdlKeycode::F18,
         keyboard::Keycode::F19 => SdlKeycode::F19,
         keyboard::Keycode::F20 => SdlKeycode::F20,
         keyboard::Keycode::F21 => SdlKeycode::F21,
         keyboard::Keycode::F22 => SdlKeycode::F22,
         keyboard::Keycode::F23 => SdlKeycode::F23,
         keyboard::Keycode::F24 => SdlKeycode::F24,
         keyboard::Keycode::Execute => SdlKeycode::Execute,
         keyboard::Keycode::Help => SdlKeycode::Help,
         keyboard::Keycode::Menu => SdlKeycode::Menu,
         keyboard::Keycode::Select => SdlKeycode::Select,
         keyboard::Keycode::Stop => SdlKeycode::Stop,
         keyboard::Keycode::Again => SdlKeycode::Again,
         keyboard::Keycode::Undo => SdlKeycode::Undo,
         keyboard::Keycode::Cut => SdlKeycode::Cut,
         keyboard::Keycode::Copy => SdlKeycode::Copy,
         keyboard::Keycode::Paste => SdlKeycode::Paste,
         keyboard::Keycode::Find => SdlKeycode::Find,
         keyboard::Keycode::Mute => SdlKeycode::Mute,
         keyboard::Keycode::VolumeUp => SdlKeycode::VolumeUp,
         keyboard::Keycode::VolumeDown => SdlKeycode::VolumeDown,
         keyboard::Keycode::KpComma => SdlKeycode::KpComma,
         keyboard::Keycode::KpEqualsAs400 => SdlKeycode::KpEqualsAs400,
         keyboard::Keycode::AltErase => SdlKeycode::AltErase,
         keyboard::Keycode::SysReq => SdlKeycode::SysReq,
         keyboard::Keycode::Cancel => SdlKeycode::Cancel,
         keyboard::Keycode::Clear => SdlKeycode::Clear,
         keyboard::Keycode::Prior => SdlKeycode::Prior,
         keyboard::Keycode::Return2 => SdlKeycode::Return2,
         keyboard::Keycode::Separator => SdlKeycode::Separator,
         keyboard::Keycode::Out => SdlKeycode::Out,
         keyboard::Keycode::Oper => SdlKeycode::Oper,
         keyboard::Keycode::ClearAgain => SdlKeycode::ClearAgain,
         keyboard::Keycode::CrSel => SdlKeycode::CrSel,
         keyboard::Keycode::ExSel => SdlKeycode::ExSel,
         keyboard::Keycode::Kp00 => SdlKeycode::Kp00,
         keyboard::Keycode::Kp000 => SdlKeycode::Kp000,
         keyboard::Keycode::ThousandsSeparator => SdlKeycode::ThousandsSeparator,
         keyboard::Keycode::DecimalSeparator => SdlKeycode::DecimalSeparator,
         keyboard::Keycode::CurrencyUnit => SdlKeycode::CurrencyUnit,
         keyboard::Keycode::CurrencySubunit => SdlKeycode::CurrencySubunit,
         keyboard::Keycode::KpLeftParen => SdlKeycode::KpLeftParen,
         keyboard::Keycode::KpRightParen => SdlKeycode::KpRightParen,
         keyboard::Keycode::KpLeftBrace => SdlKeycode::KpLeftBrace,
         keyboard::Keycode::KpRightBrace => SdlKeycode::KpRightBrace,
         keyboard::Keycode::KpTab => SdlKeycode::KpTab,
         keyboard::Keycode::KpBackspace => SdlKeycode::KpBackspace,
         keyboard::Keycode::KpA => SdlKeycode::KpA,
         keyboard::Keycode::KpB => SdlKeycode::KpB,
         keyboard::Keycode::KpC => SdlKeycode::KpC,
         keyboard::Keycode::KpD => SdlKeycode::KpD,
         keyboard::Keycode::KpE => SdlKeycode::KpE,
         keyboard::Keycode::KpF => SdlKeycode::KpF,
         keyboard::Keycode::KpXor => SdlKeycode::KpXor,
         keyboard::Keycode::KpPower => SdlKeycode::KpPower,
         keyboard::Keycode::KpPercent => SdlKeycode::KpPercent,
         keyboard::Keycode::KpLess => SdlKeycode::KpLess,
         keyboard::Keycode::KpGreater => SdlKeycode::KpGreater,
         keyboard::Keycode::KpAmpersand => SdlKeycode::KpAmpersand,
         keyboard::Keycode::KpDblAmpersand => SdlKeycode::KpDblAmpersand,
         keyboard::Keycode::KpVerticalBar => SdlKeycode::KpVerticalBar,
         keyboard::Keycode::KpDblVerticalBar => SdlKeycode::KpDblVerticalBar,
         keyboard::Keycode::KpColon => SdlKeycode::KpColon,
         keyboard::Keycode::KpHash => SdlKeycode::KpHash,
         keyboard::Keycode::KpSpace => SdlKeycode::KpSpace,
         keyboard::Keycode::KpAt => SdlKeycode::KpAt,
         keyboard::Keycode::KpExclam => SdlKeycode::KpExclam,
         keyboard::Keycode::KpMemStore => SdlKeycode::KpMemStore,
         keyboard::Keycode::KpMemRecall => SdlKeycode::KpMemRecall,
         keyboard::Keycode::KpMemClear => SdlKeycode::KpMemClear,
         keyboard::Keycode::KpMemAdd => SdlKeycode::KpMemAdd,
         keyboard::Keycode::KpMemSubtract => SdlKeycode::KpMemSubtract,
         keyboard::Keycode::KpMemMultiply => SdlKeycode::KpMemMultiply,
         keyboard::Keycode::KpMemDivide => SdlKeycode::KpMemDivide,
         keyboard::Keycode::KpPlusMinus => SdlKeycode::KpPlusMinus,
         keyboard::Keycode::KpClear => SdlKeycode::KpClear,
         keyboard::Keycode::KpClearEntry => SdlKeycode::KpClearEntry,
         keyboard::Keycode::KpBinary => SdlKeycode::KpBinary,
         keyboard::Keycode::KpOctal => SdlKeycode::KpOctal,
         keyboard::Keycode::KpDecimal => SdlKeycode::KpDecimal,
         keyboard::Keycode::KpHexadecimal => SdlKeycode::KpHexadecimal,
         keyboard::Keycode::LCtrl => SdlKeycode::LCtrl,
         keyboard::Keycode::LShift => SdlKeycode::LShift,
         keyboard::Keycode::LAlt => SdlKeycode::LAlt,
         keyboard::Keycode::LGui => SdlKeycode::LGui,
         keyboard::Keycode::RCtrl => SdlKeycode::RCtrl,
         keyboard::Keycode::RShift => SdlKeycode::RShift,
         keyboard::Keycode::RAlt => SdlKeycode::RAlt,
         keyboard::Keycode::RGui => SdlKeycode::RGui,
         keyboard::Keycode::Mode => SdlKeycode::Mode,
         keyboard::Keycode::Sleep => SdlKeycode::Sleep,
         keyboard::Keycode::Wake => SdlKeycode::Wake,
         keyboard::Keycode::ChannelIncrement => SdlKeycode::ChannelIncrement,
         keyboard::Keycode::ChannelDecrement => SdlKeycode::ChannelDecrement,
         keyboard::Keycode::MediaPlay => SdlKeycode::MediaPlay,
         keyboard::Keycode::MediaPause => SdlKeycode::MediaPause,
         keyboard::Keycode::MediaRecord => SdlKeycode::MediaRecord,
         keyboard::Keycode::MediaFastForward => SdlKeycode::MediaFastForward,
         keyboard::Keycode::MediaRewind => SdlKeycode::MediaRewind,
         keyboard::Keycode::MediaNextTrack => SdlKeycode::MediaNextTrack,
         keyboard::Keycode::MediaPreviousTrack => SdlKeycode::MediaPreviousTrack,
         keyboard::Keycode::MediaStop => SdlKeycode::MediaStop,
         keyboard::Keycode::MediaEject => SdlKeycode::MediaEject,
         keyboard::Keycode::MediaPlayPause => SdlKeycode::MediaPlayPause,
         keyboard::Keycode::MediaSelect => SdlKeycode::MediaSelect,
         keyboard::Keycode::AcNew => SdlKeycode::AcNew,
         keyboard::Keycode::AcOpen => SdlKeycode::AcOpen,
         keyboard::Keycode::AcClose => SdlKeycode::AcClose,
         keyboard::Keycode::AcExit => SdlKeycode::AcExit,
         keyboard::Keycode::AcSave => SdlKeycode::AcSave,
         keyboard::Keycode::AcPrint => SdlKeycode::AcPrint,
         keyboard::Keycode::AcProperties => SdlKeycode::AcProperties,
         keyboard::Keycode::AcSearch => SdlKeycode::AcSearch,
         keyboard::Keycode::AcHome => SdlKeycode::AcHome,
         keyboard::Keycode::AcBack => SdlKeycode::AcBack,
         keyboard::Keycode::AcForward => SdlKeycode::AcForward,
         keyboard::Keycode::AcStop => SdlKeycode::AcStop,
         keyboard::Keycode::AcRefresh => SdlKeycode::AcRefresh,
         keyboard::Keycode::AcBookmarks => SdlKeycode::AcBookmarks,
         keyboard::Keycode::SoftLeft => SdlKeycode::SoftLeft,
         keyboard::Keycode::SoftRight => SdlKeycode::SoftRight,
         keyboard::Keycode::Call => SdlKeycode::Call,
         keyboard::Keycode::EndCall => SdlKeycode::EndCall,
      }
   }
}
